name: Macos_arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install and set up SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          echo "SDKMAN_DIR=$HOME/.sdkman" >> $GITHUB_ENV
          echo "$HOME/.sdkman/bin" >> $GITHUB_PATH
          
      - name:  用sdkman下载jdk
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 25.ea.36-open
          sdk use java 25.ea.36-open
          java -version
      - name:  处理前置依赖
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          # --- 1. 处理 oyzh1994/base 依赖 ---
          git clone --depth 1 --branch v1.0.2  https://github.com/oyzh1994/base.git
          cd base
          mvn clean install -DskipTests
          cd ..
          rm -rf base
          # --- 2. 处理 oyzh1994/fx-base 依赖 ---
          git clone --depth 1 --branch v1.3.5 https://github.com/oyzh1994/fx-base.git
          cd fx-base
          mvn clean install -DskipTests
          cd ..
          rm -rf fx-base

      - name:  打包项目jar
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          mvn -X clean package -DskipTests

      - name: 执行项目打包
        run: |
          # 确保SDKMAN环境变量被正确加载
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          # 动态查找JAR包文件
          # -name "*.jar" 匹配所有以 .jar 结尾的文件
          # -print -quit 找到第一个匹配的文件后立即退出
          JAR_FILE=$(find target -name "*.jar" -print -quit)
          # 提取JAR文件名，例如 easyshell-1.0-SNAPSHOT.jar
          JAR_NAME=$(basename "$JAR_FILE")
          # 检查JAR文件是否找到
          if [ -z "$JAR_FILE" ]; then
          echo "Error: Main JAR file not found in target directory."
          exit 1
          fi
          APP_NAME="EasyShell"   
          APP_VERSION=$(echo "$JAR_NAME" | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*)\.jar/\1/')
          echo "JAR file: $JAR_FILE"
          echo "APP_NAME: $APP_NAME"
          echo "APP_VERSION: $APP_VERSION"
          
          jlink \
          --verbose \
          --vm=server \
          --compress=2 \ 
          --strip-debug \
          --no-man-pages \
          --no-header-files \ 
          --output runtime_jre \
          --strip-java-debug-attributes \ 
          --add-modules java.xml,java.rmi,java.sql,java.base,java.logging,java.scripting,java.desktop,java.management,java.datatransfer,java.security.jgss,jdk.unsupported \

          jpackage \
            --verbose \
            --type pkg \
            --dest dist \
            --input target \
            --vendor "oyzh" \
            --name "$APP_NAME" \
            --main-jar "$JAR_NAME" \
            --icon resource/app.icns \
            --runtime-image runtime_jre \
            --app-version "$APP_VERSION" \
            --mac-package-identifier cn.oyzh.easyshell \
            --description '功能强大、现代化、跨平台的多协议客户端.' \

      - name: 显示项目结构
        run: |
          brew install tree
          echo "--- 项目目录结构 ---"
          tree -L 3
          
      - name: 列举生成的构建物
        run: ls -lh dist

      - name: 上传构建物
        uses: actions/upload-artifact@v4
        with:
          name: easyshell-pkg
          path: dist/*.pkg
